"""a2c: translate arm64 machine code from ELF shared libraries into C, one C function per original function.

The generated C keeps the original's memory layout (the library is mapped at run time and pointers are real
pointers), so results are the original's bit for bit as long as each instruction is translated faithfully.
Nothing generated by this tool belongs in the repository: it is a derivative of the library it was run on.

Model (see a2c_rt.h):
  - every function is `void F_<image>_<address>(cpu_t *c)`; registers live in C locals inside it.
  - at a call the argument registers (x0-x8, v0-v7, sp) are written to `c`, and x0, x1, v0-v3 read back after.
    Nothing else crosses a call: callee-saved registers stay in the caller's locals, which is what the ABI
    promises the caller anyway.
  - image addresses are compile-time constants (the images are mapped at fixed bases).
  - calls through the import table are bound at translation time: to another translated function, or to a
    host function H_<name> written in C.
"""
import re, struct, sys, collections
from capstone import Cs, CS_ARCH_ARM64, CS_MODE_ARM

U64 = 0xFFFFFFFFFFFFFFFF


class Elf:
    def __init__(self, path, index, base):
        self.path, self.index, self.base = path, index, base
        self.d = d = open(path, "rb").read()
        phoff, = struct.unpack_from("<Q", d, 0x20)
        pes, pn = struct.unpack_from("<HH", d, 0x36)
        self.ph = [struct.unpack_from("<IIQQQQQQ", d, phoff + i * pes) for i in range(pn)]
        shoff, = struct.unpack_from("<Q", d, 0x28)
        es, n, sx = struct.unpack_from("<HHH", d, 0x3A)
        sh = [struct.unpack_from("<IIQQQQIIQQ", d, shoff + i * es) for i in range(n)]
        stro = sh[sx][4]
        self.sec = {d[stro + x[0]:d.index(b"\0", stro + x[0])].decode(): x for x in sh}
        dyn, ds = self.sec[".dynsym"], self.sec[".dynstr"]
        self.syms = []          # (name, value, size, shndx, type)
        for i in range(dyn[5] // 24):
            nm, info, oth, ndx, val, size = struct.unpack_from("<IBBHQQ", d, dyn[4] + i * 24)
            self.syms.append((d[ds[4] + nm:d.index(b"\0", ds[4] + nm)].decode(), val, size, ndx, info & 15))
        self.exports = {s[0]: s[1] for s in self.syms if s[3] and s[0]}
        self.byaddr = {}
        for s in self.syms:
            if s[3] and s[4] == 2:
                self.byaddr.setdefault(s[1], s[0])
        self.pltgot = {}        # got slot address -> symbol name
        if ".rela.plt" in self.sec:
            rp = self.sec[".rela.plt"]
            for i in range(rp[5] // 24):
                off, info, add = struct.unpack_from("<QQq", d, rp[4] + i * 24)
                self.pltgot[off] = self.syms[info >> 32][0]
        p = self.sec.get(".plt")
        self.plt = (p[3], p[3] + p[5]) if p else (0, 0)
        t = self.sec[".text"]
        self.text = (t[3], t[3] + t[5])
        self.md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
        self.funcs = self._functions()
        self.starts = sorted(self.funcs)
        self.relmap = {}        # data slot -> image address stored there by a relocation
        rd = self.sec.get(".rela.dyn")
        if rd:
            for i in range(rd[5] // 24):
                off, info, add = struct.unpack_from("<QQq", d, rd[4] + i * 24)
                t = info & 0xFFFFFFFF
                if t == 1027:
                    self.relmap[off] = add & U64
                elif t in (257, 1025):
                    sym = self.syms[info >> 32]
                    if sym[3]:
                        self.relmap[off] = (sym[1] + (add if t == 257 else 0)) & U64
        self.objects = sorted((s[1], s[2]) for s in self.syms if s[3] and s[4] == 1 and s[2])
        self.relslots = sorted(self.relmap)

    def code_pointers(self, addr):
        """Function addresses reachable from the data at addr: the whole object if a symbol covers it (a vtable,
        a table of handlers), else the run of pointer slots starting there."""
        import bisect
        out = []
        i = bisect.bisect_right(self.objects, (addr, 1 << 62)) - 1
        if i >= 0 and self.objects[i][0] <= addr < self.objects[i][0] + self.objects[i][1]:
            lo, hi = self.objects[i][0], self.objects[i][0] + self.objects[i][1]
            j = bisect.bisect_left(self.relslots, lo)
            while j < len(self.relslots) and self.relslots[j] < hi:
                t = self.relmap[self.relslots[j]]
                if t in self.funcs:
                    out.append(t)
                j += 1
            return out
        a = addr
        for _ in range(64):
            t = self.relmap.get(a)
            if t is None or t not in self.funcs:
                break
            out.append(t)
            a += 8
        return out

    def off(self, va):
        for t, fl, o, v, pa, fs, ms, al in self.ph:
            if t == 1 and v <= va < v + fs:
                return o + va - v
        return None

    def read(self, va, n):
        o = self.off(va)
        return self.d[o:o + n]

    def _functions(self):
        """{start: size} from .eh_frame FDEs and the dynamic symbols."""
        f = {}
        for s in self.syms:
            if s[3] and s[4] == 2 and s[2] and self.text[0] <= s[1] < self.text[1]:
                f[s[1]] = max(f.get(s[1], 0), s[2])
        sec = self.sec.get(".eh_frame")
        if sec:
            d, off, va, end = self.d, sec[4], sec[3], sec[4] + sec[5]
            cies, p = {}, off

            def uleb(q):
                v = sh = 0
                while True:
                    b = d[q]; q += 1
                    v |= (b & 0x7F) << sh; sh += 7
                    if not b & 0x80:
                        return v, q

            def enc_read(q, enc):
                fmt = {0: "<Q", 2: "<H", 3: "<I", 4: "<Q", 0xA: "<h", 0xB: "<i", 0xC: "<q"}[enc & 0xF]
                v, = struct.unpack_from(fmt, d, q)
                if (enc & 0x70) == 0x10:
                    v += va + (q - off)
                return v & U64, q + struct.calcsize(fmt)

            while p + 4 <= end:
                length, = struct.unpack_from("<I", d, p)
                if length == 0:
                    break
                start = p + 4
                cid, = struct.unpack_from("<I", d, start)
                if cid == 0:
                    q = start + 5
                    e = d.index(b"\0", q); aug = d[q:e].decode(); q = e + 1
                    _, q = uleb(q); _, q = uleb(q)          # alignment factors (sleb read as uleb: same length)
                    if d[start + 4] == 1:
                        q += 1
                    else:
                        _, q = uleb(q)
                    fde_enc = 0
                    if aug.startswith("z"):
                        _, q = uleb(q)
                        for ch in aug[1:]:
                            if ch == "R":
                                fde_enc = d[q]; q += 1
                            elif ch == "P":
                                pe = d[q]; q += 1
                                _, q = enc_read(q, pe)
                            elif ch == "L":
                                q += 1
                    cies[p] = fde_enc
                else:
                    enc = cies.get(start - cid, 0x1B)
                    begin, q = enc_read(start + 4, enc)
                    size, q = enc_read(q, enc & 0xF)
                    if size and self.text[0] <= begin < self.text[1]:
                        f[begin] = max(f.get(begin, 0), size)
                p = start + length
        return f

    def plt_target(self, va):
        """The symbol a PLT stub jumps to, or None."""
        ins = list(self.md.disasm(self.read(va, 16), va))
        if len(ins) >= 2 and ins[0].mnemonic == "adrp" and ins[1].mnemonic == "ldr":
            page = int(ins[0].op_str.split("#")[1], 0)
            m = re.search(r"#(0x[0-9a-f]+|\d+)\]", ins[1].op_str)
            return self.pltgot.get(page + (int(m.group(1), 0) if m else 0))
        return None


# ---------------------------------------------------------------------------------------------------------
# operands

CONDS = {"eq": "zf", "ne": "!zf", "hs": "cf", "cs": "cf", "lo": "!cf", "cc": "!cf", "mi": "nf", "pl": "!nf",
         "vs": "vf", "vc": "!vf", "hi": "(cf && !zf)", "ls": "(!cf || zf)", "ge": "(nf == vf)",
         "lt": "(nf != vf)", "gt": "(!zf && nf == vf)", "le": "(zf || nf != vf)", "al": "1", "nv": "1"}
INVERT = {"eq": "ne", "ne": "eq", "hs": "lo", "cs": "lo", "lo": "hs", "cc": "hs", "mi": "pl", "pl": "mi",
          "vs": "vc", "vc": "vs", "hi": "ls", "ls": "hi", "ge": "lt", "lt": "ge", "gt": "le", "le": "gt"}
FLD = {8: "b", 16: "h", 32: "w", 64: "q"}
SFLD = {8: "sb", 16: "sh", 32: "sw", 64: "sq"}
FFLD = {32: "f", 64: "d"}
UT = {8: "uint8_t", 16: "uint16_t", 32: "uint32_t", 64: "uint64_t"}
ST = {8: "int8_t", 16: "int16_t", 32: "int32_t", 64: "int64_t"}
FT = {32: "float", 64: "double"}
ESZ = {"b": 8, "h": 16, "s": 32, "d": 64, "q": 128}


class Op:
    def __init__(self, kind, **kw):
        self.kind = kind
        self.__dict__.update(kw)

    def __repr__(self):
        return "Op(%s)" % ", ".join("%s=%r" % kv for kv in self.__dict__.items())


def split_ops(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip()); cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def parse_imm(t):
    t = t.lstrip("#")
    if re.fullmatch(r"-?0x[0-9a-fA-F]+", t):
        return int(t, 16)
    if re.fullmatch(r"-?\d+", t):
        return int(t, 10) if not (len(t) > 1 and t.startswith("0") and set(t) == {"0"}) else 0
    return float(t)


def parse_reg(t):
    m = re.fullmatch(r"([xw])(\d+)", t)
    if m:
        return Op("g", n=int(m.group(2)), w=64 if m.group(1) == "x" else 32)
    if t in ("sp", "wsp"):
        return Op("sp", w=64 if t == "sp" else 32)
    if t in ("xzr", "wzr"):
        return Op("zr", w=64 if t == "xzr" else 32)
    if t == "fp":
        return Op("g", n=29, w=64)
    if t == "lr":
        return Op("g", n=30, w=64)
    m = re.fullmatch(r"([bhsdq])(\d+)", t)
    if m:
        return Op("fs", n=int(m.group(2)), w=ESZ[m.group(1)])
    m = re.fullmatch(r"v(\d+)\.(\d*)([bhsd])\[(0x[0-9a-f]+|\d+)\]", t)
    if m:
        return Op("ve", n=int(m.group(1)), es=ESZ[m.group(3)], idx=int(m.group(4), 0))
    m = re.fullmatch(r"v(\d+)\.(\d+)([bhsd])", t)
    if m:
        return Op("v", n=int(m.group(1)), cnt=int(m.group(2)), es=ESZ[m.group(3)])
    m = re.fullmatch(r"v(\d+)\.1q", t)
    if m:
        return Op("v", n=int(m.group(1)), cnt=1, es=128)
    return None


def parse_op(t):
    r = parse_reg(t)
    if r:
        return r
    if t.startswith("#"):
        return Op("imm", v=parse_imm(t))
    if t.startswith("["):
        pre = t.endswith("!")
        inner = t.rstrip("!")[1:-1]
        parts = [p.strip() for p in inner.split(",")]
        base = parse_reg(parts[0])
        o = Op("mem", base=base, index=None, ext=None, shift=0, disp=0, pre=pre)
        if len(parts) >= 2:
            if parts[1].startswith("#"):
                o.disp = parse_imm(parts[1])
            else:
                o.index = parse_reg(parts[1])
                if len(parts) >= 3:
                    m = re.fullmatch(r"(\w+)(?:\s+#(\d+))?", parts[2])
                    o.ext, o.shift = m.group(1), int(m.group(2) or 0)
        return o
    if t.startswith("{"):
        m = re.fullmatch(r"\{(.*)\}(?:\[(\d+)\])?", t)
        regs = [x.strip() for x in m.group(1).split(",")]
        if len(regs) == 1 and " - " in regs[0]:
            a, b = [x.strip() for x in regs[0].split(" - ")]
            ra, rb = parse_reg(a if "." in a else a), parse_reg(b)
            suffix = a[a.index("."):]
            regs = ["v%d%s" % (k % 32, suffix) for k in range(ra.n, ra.n + ((rb.n - ra.n) % 32) + 1)]
        idx = m.group(2)
        ops = []
        for x in regs:
            if idx is not None:
                mm = re.fullmatch(r"v(\d+)\.([bhsd])", x)
                ops.append(Op("ve", n=int(mm.group(1)), es=ESZ[mm.group(2)], idx=int(idx)))
            else:
                ops.append(parse_reg(x))
        return Op("list", regs=ops)
    m = re.fullmatch(r"(lsl|lsr|asr|ror|msl)\s+#(\d+)", t)
    if m:
        return Op("shift", t=m.group(1), amt=int(m.group(2)))
    m = re.fullmatch(r"([us]xt[bhwx])(?:\s+#(\d+))?", t)
    if m:
        return Op("ext", t=m.group(1), amt=int(m.group(2) or 0))
    if t in CONDS:
        return Op("cond", c=t)
    return Op("sym", name=t)


class Unsupported(Exception):
    pass


# ---------------------------------------------------------------------------------------------------------
# translation of one function

class Func:
    def __init__(self, tr, img, start, size):
        self.tr, self.img, self.start, self.size = tr, img, start, size
        self.end = start + size
        self.lines = []
        self.callees = set()
        self.unsupported = []

    # ---- general registers
    def g(self, o, signed=False):
        """C expression for a general register operand at its own width."""
        if o.kind == "zr":
            return "0"
        if o.kind == "sp":
            return "sp" if o.w == 64 else "(uint32_t)sp"
        if o.kind == "imm":
            return self.imm(o.v, 64)
        if o.kind != "g":
            raise Unsupported("general register expected: %r" % o)
        if o.w == 64:
            return ("(int64_t)x%d" if signed else "x%d") % o.n
        return ("(int32_t)x%d" if signed else "(uint32_t)x%d") % o.n

    def setg(self, o, expr):
        if o.kind == "zr":
            return "(void)(%s);" % expr
        if o.kind == "sp":
            return "sp = (uint64_t)(%s);" % expr if o.w == 64 else "sp = (uint32_t)(%s);" % expr
        if o.kind != "g":
            raise Unsupported("general register expected: %r" % o)
        return "x%d = (%s)(%s);" % (o.n, "uint64_t" if o.w == 64 else "uint32_t", expr)

    def imm(self, v, w):
        if isinstance(v, float):
            raise Unsupported("float immediate where integer expected")
        v &= (1 << w) - 1
        return "0x%xULL" % v if w == 64 else "0x%xU" % v

    def op2(self, ops, w):
        """Second operand of a data-processing instruction: register or immediate, with shift or extend."""
        o = ops[0]
        mod = ops[1] if len(ops) > 1 else None
        ut = UT[w]
        if o.kind == "imm":
            v = o.v
            if mod and mod.kind == "shift" and mod.t == "lsl":
                v <<= mod.amt
            return self.imm(v, w)
        if mod is None:
            return "(%s)%s" % (ut, self.g(o)) if o.kind in ("g", "sp") else self.g(o)
        if mod.kind == "shift":
            r = self.g(o)
            if mod.amt == 0:
                return "(%s)%s" % (ut, r)
            if mod.t == "lsl":
                return "((%s)%s << %d)" % (ut, r, mod.amt)
            if mod.t == "lsr":
                return "((%s)%s >> %d)" % (ut, r, mod.amt)
            if mod.t == "asr":
                return "(%s)((%s)%s >> %d)" % (ut, ST[w], r, mod.amt)
            if mod.t == "ror":
                return "ror%d(%s, %d)" % (w, r, mod.amt)
        if mod.kind == "ext":
            src = {"b": 8, "h": 16, "w": 32, "x": 64}[mod.t[3]]
            raw = "x%d" % o.n if o.kind == "g" else ("0" if o.kind == "zr" else "sp")
            t = (ST if mod.t[0] == "s" else UT)[src]
            e = "(%s)(%s)(%s)%s" % (ut, ST[w] if mod.t[0] == "s" else ut, t, raw)
            return "(%s << %d)" % (e, mod.amt) if mod.amt else e
        raise Unsupported("operand modifier %r" % mod)

    # ---- memory
    def addr(self, m):
        """(address expression, statement to run after for writeback or '')."""
        base = "sp" if m.base.kind == "sp" else "x%d" % m.base.n
        if m.index is not None:
            idx = m.index
            raw = "x%d" % idx.n if idx.kind == "g" else "0"
            if m.ext in (None, "lsl", "uxtx", "sxtx"):
                e = "(uint64_t)%s" % raw if idx.w == 64 else "(uint64_t)(uint32_t)%s" % raw
            elif m.ext == "uxtw":
                e = "(uint64_t)(uint32_t)%s" % raw
            elif m.ext == "sxtw":
                e = "(uint64_t)(int64_t)(int32_t)%s" % raw
            else:
                raise Unsupported("index extend %s" % m.ext)
            if m.shift:
                e = "(%s << %d)" % (e, m.shift)
            return "(%s + %s)" % (base, e), ""
        if m.disp:
            a = "(%s + %s)" % (base, self.imm(m.disp, 64))
        else:
            a = base
        return a, ("%s = %s;" % (base, a) if m.pre else "")

    def mem_access(self, ops, k):
        """ops[k] is a memory operand, possibly followed by a post-index operand. Returns (address, pre statement,
        post statement). With pre-indexing the base is updated first and then used."""
        m = ops[k]
        if m.kind == "imm":      # pc-relative literal
            return "(IMG%d + 0x%xULL)" % (self.img.index, m.v), "", ""
        a, wb = self.addr(m)
        base = "sp" if m.base.kind == "sp" else "x%d" % m.base.n
        if m.pre:
            return base, wb, ""
        post = ""
        if len(ops) > k + 1:
            p = ops[k + 1]
            if p.kind == "imm":
                post = "%s += %s;" % (base, self.imm(p.v, 64))
            elif p.kind == "g":
                post = "%s += x%d;" % (base, p.n)
        return a, "", post

    # ---- simd helpers
    def fsr(self, o, signed=False):
        """Scalar read of an fp/simd register at its width: float for 32, double for 64."""
        if o.kind == "ve":
            return "v%d.%s[%d]" % (o.n, FFLD[o.es], o.idx)
        if o.w in (32, 64):
            return "v%d.%s[0]" % (o.n, FFLD[o.w])
        raise Unsupported("scalar float width %d" % o.w)

    def fsbits(self, o):
        if o.kind == "ve":
            return "v%d.%s[%d]" % (o.n, FLD[o.es], o.idx)
        return "v%d.%s[0]" % (o.n, FLD[o.w])

    def setfs(self, o, expr):
        """Write a scalar float result; the rest of the register is cleared."""
        return "v%d = mk_%s(%s);" % (o.n, FFLD[o.w], expr)

    def setbits(self, o, expr):
        return "v%d = mk_%s(%s);" % (o.n, FLD[o.w], expr)

    def vec(self, d, expr, fld=None, cnt=None, es=None, keep=False):
        """Per-lane vector statement. expr is a C expression in i. Sources are read before the result is written."""
        cnt = cnt or d.cnt
        es = es or d.es
        fld = fld or FLD[es]
        init = "t = v%d;" % d.n if keep else "t.q[0] = t.q[1] = 0;"
        return "{ V t; %s for (int i = 0; i < %d; i++) t.%s[i] = %s; v%d = t; }" % (init, cnt, fld, expr, d.n)

    def lane(self, o, fld=None, es=None):
        """Lane i of a vector operand, or the fixed element of an element operand."""
        if o.kind == "ve":
            return "v%d.%s[%d]" % (o.n, fld or FLD[o.es], o.idx)
        if o.kind == "v":
            return "v%d.%s[i]" % (o.n, fld or FLD[es or o.es])
        raise Unsupported("vector operand expected: %r" % o)

    # ---- flags
    def flags_sub(self, a, b, w):
        t = UT[w]
        return ("{ %s a_ = %s, b_ = %s, r_ = a_ - b_; nf = r_ >> %d; zf = r_ == 0; cf = a_ >= b_; "
                "vf = ((a_ ^ b_) & (a_ ^ r_)) >> %d; RES }" % (t, a, b, w - 1, w - 1))

    def flags_add(self, a, b, w):
        t = UT[w]
        return ("{ %s a_ = %s, b_ = %s, r_ = a_ + b_; nf = r_ >> %d; zf = r_ == 0; cf = r_ < a_; "
                "vf = (~(a_ ^ b_) & (a_ ^ r_)) >> %d; RES }" % (t, a, b, w - 1, w - 1))

    def fcmp(self, a, b):
        return ("{ __typeof__(%s) a_ = %s, b_ = %s; if (a_ != a_ || b_ != b_) { nf = 0; zf = 0; cf = 1; vf = 1; } "
                "else if (a_ == b_) { nf = 0; zf = 1; cf = 1; vf = 0; } else if (a_ < b_) { nf = 1; zf = 0; cf = 0; vf = 0; } "
                "else { nf = 0; zf = 0; cf = 1; vf = 0; } }" % (a, a, b))

    def nzcv(self, v):
        return "nf = %d; zf = %d; cf = %d; vf = %d;" % ((v >> 3) & 1, (v >> 2) & 1, (v >> 1) & 1, v & 1)

    # ---- control flow
    def label(self, a):
        return "L_%x" % a

    def call_target(self, target):
        """C statement calling the function at `target` in this image (through the PLT if it is a stub)."""
        img = self.img
        if img.plt[0] <= target < img.plt[1]:
            name = img.plt_target(target)
            if name is None:
                raise Unsupported("PLT stub at %x not understood" % target)
            return self.tr.call_symbol(self, name)
        if target in img.funcs:
            self.callees.add((img.index, target))
            return "F_%d_%x(c);" % (img.index, target)
        raise Unsupported("call into the middle of a function: %x" % target)

    def sync_out(self):
        return "SO"

    def emit(self, s):
        self.lines.append("  " + s)

    def translate(self):
        img = self.img
        code = img.read(self.start, self.size)
        insns = []
        a = self.start
        while a < self.end:
            got = list(img.md.disasm(code[a - self.start:a - self.start + 4], a))
            insns.append(got[0] if got else None)
            a += 4
        targets = set()
        has_br = False
        for i in insns:
            if i is None:
                continue
            if i.mnemonic == "br":
                has_br = True
            if i.mnemonic in ("b", "cbz", "cbnz", "tbz", "tbnz") or i.mnemonic.startswith("b."):
                t = int(i.op_str.split("#")[-1], 0)
                if self.start <= t < self.end:
                    targets.add(t)
        self.has_br = has_br
        self.br_cases = None
        # where a jump table could land: after an unconditional transfer, or where a branch goes
        self.leaders = set(targets)
        for k, i in enumerate(insns):
            if i is not None and i.mnemonic in ("b", "ret", "br"):
                self.leaders.add(self.start + 4 * k + 4)
        if has_br:
            cases = self.jump_tables(insns)
            if cases is None:
                # a computed jump that was not understood: any instruction may be a target
                targets = set(range(self.start, self.end, 4))
                self.tr.unresolved_br += 1
                self.tr.unresolved_list.append((self.img.index, self.start))
            else:
                self.br_cases = sorted(cases)
                targets |= cases
        page = {}       # register -> address from the last adrp/adr
        for k, i in enumerate(insns):
            addr = self.start + 4 * k
            if i is not None:
                self.note_addresses(i, page)
            if addr in targets:
                self.lines.append("%s: ;" % self.label(addr))
            if i is None:
                self.emit("a2c_trap(c, 0x%xULL, \"undecoded\");" % addr)
                continue
            try:
                ops = [parse_op(t) for t in split_ops(i.op_str)]
                out = self.insn(i.mnemonic, ops, addr, i)
            except Unsupported as e:
                self.unsupported.append((addr, i.mnemonic, i.op_str, str(e)))
                out = ["a2c_trap(c, 0x%xULL, \"unsupported: %s %s\");" % (addr, i.mnemonic, i.op_str.replace('"', "'"))]
            except KeyError as e:
                if e.args and e.args[0] == 16:
                    self.unsupported.append((addr, i.mnemonic, i.op_str, "half-precision arithmetic"))
                    out = ["a2c_trap(c, 0x%xULL, \"half-precision arithmetic\");" % addr]
                else:
                    self.unsupported.append((addr, i.mnemonic, i.op_str, "translator error: %r" % e))
                    out = ["a2c_trap(c, 0x%xULL, \"translator error\");" % addr]
            except Exception as e:      # a translator bug: record it against the instruction
                self.unsupported.append((addr, i.mnemonic, i.op_str, "translator error: %r" % e))
                out = ["a2c_trap(c, 0x%xULL, \"translator error: %s %s\");" % (addr, i.mnemonic, i.op_str.replace('"', "'"))]
            for s in out:
                self.emit(s + ("  /*%x*/" % addr if s is out[0] else ""))
        self.emit("a2c_trap(c, 0x%xULL, \"fell off the end\");" % self.end)
        return self.render()

    def note_addresses(self, i, page):
        """Follow addresses the code materialises: a function's address makes it a root, and so do the functions
        a referenced object points to (this is how virtual functions and callbacks are found)."""
        img = self.img
        m, ops = i.mnemonic, [t.strip() for t in split_ops(i.op_str)]
        if m in ("adrp", "adr"):
            v = int(ops[1].lstrip("#"), 0)
            page[ops[0]] = v
            if m == "adr":
                self.address_seen(v)
            return
        cand = None
        if m == "add" and len(ops) == 3 and ops[1] in page and ops[2].startswith("#"):
            cand = page[ops[1]] + int(ops[2].lstrip("#"), 0)
            page[ops[0]] = cand if ops[0] != ops[1] else cand
            self.address_seen(cand)
            return
        if m in ("ldr", "ldrsw") and len(ops) == 2:
            mm = re.fullmatch(r"\[(x\d+)(?:, #(0x[0-9a-f]+|\d+))?\]", ops[1])
            if mm and mm.group(1) in page:
                slot = page[mm.group(1)] + int(mm.group(2) or "0", 0)
                t = img.relmap.get(slot)
                if t is not None:
                    self.address_seen(t)
        # any other write to a register forgets what it held
        if ops and ops[0] in page and m not in ("cmp", "tst", "str", "stp", "strb", "strh", "stur", "cbz", "cbnz", "tbz", "tbnz"):
            del page[ops[0]]

    def address_seen(self, a):
        img = self.img
        if a in img.funcs:
            if not (img.plt[0] <= a < img.plt[1]):
                self.callees.add((img.index, a))
        elif not (img.text[0] <= a < img.text[1]):
            for t in img.code_pointers(a):
                self.callees.add((img.index, t))

    def jump_tables(self, insns):
        """Targets of every jump table in the function, or None if a computed jump is not understood.

        The compiler's shapes, all ending `add xN, xB, xE(, lsl #2); ...; br xN` with xB from `adr`:
          ldrb/ldrh wE, [xT, xI(, lsl #1)]   entries count instructions from the adr address
          ldrsw xE, [xT, xI, lsl #2]         entries are byte offsets from the adr address
        The table xT comes from `adrp`+`add` (possibly far earlier, in a register that holds nothing else), and
        the bound from the `cmp xI, #n` or `cmp xI, xC` (xC a constant) guarding it. A `br` with no `adr` just
        before it is an indirect tail call and has no targets here.
        """
        img = self.img
        out = set()
        txt_all = [(j, x.mnemonic, [t.strip() for t in split_ops(x.op_str)]) for j, x in enumerate(insns) if x is not None]

        def reg_names(r):
            return ("x" + r[1:], "w" + r[1:])

        def whole_function_const(r):
            """The address in r if the only thing the function ever puts in r is one adrp(+add) or adr."""
            defs = [t for t in txt_all if t[2] and t[2][0] in reg_names(r) and t[1] not in
                    ("cmp", "tst", "str", "stp", "strb", "strh", "stur", "cbz", "cbnz", "tbz", "tbnz", "cmn", "b", "br", "blr", "ccmp")]
            if not defs or defs[0][1] not in ("adr", "adrp"):
                return None
            v = int(defs[0][2][1].lstrip("#"), 0)
            rest = defs[1:]
            if defs[0][1] == "adrp" and rest and rest[0][1] == "add" and rest[0][2][1] == r and rest[0][2][2].startswith("#"):
                v += int(rest[0][2][2].lstrip("#"), 0)
                rest = rest[1:]
            # callee-saved registers are also restored by ldp/ldr in the epilogue
            if any(t[1] not in ("ldp", "ldr") for t in rest):
                return None
            return v

        for k, i in enumerate(insns):
            if i is None or i.mnemonic != "br":
                continue
            reg = i.op_str.strip()
            txt = [t for t in txt_all if max(0, k - 40) <= t[0] < k]
            if not any(t[1] == "adr" for t in txt[-10:]):
                continue        # indirect tail call
            add = next((t for t in reversed(txt[-10:]) if t[1] == "add" and t[2][0] == reg and len(t[2]) >= 3), None)
            if add is None:
                return self.jt_fail(i.address)
            j_add, _, o = add
            before = [t for t in txt if t[0] < j_add]

            def last(pred):
                return next((t for t in reversed(before) if pred(t)), None)

            def const_of(r):
                t = last(lambda t: t[1] in ("adr", "adrp") and t[2][0] == r)
                if t is None:
                    return whole_function_const(r)
                v = int(t[2][1].lstrip("#"), 0)
                if t[1] == "adrp":
                    t2 = next((u for u in before if u[0] > t[0] and u[1] == "add" and u[2][0] == r and u[2][1] == r
                               and len(u[2]) == 3 and u[2][2].startswith("#")), None)
                    if t2:
                        v += int(t2[2][2].lstrip("#"), 0)
                return v

            def reg_const(r, upto):
                """Value a mov(+movk) sequence leaves in r before instruction `upto`."""
                seq = [t for t in before if t[0] < upto and t[2] and t[2][0] in reg_names(r)]
                v = None
                for t in seq:
                    if t[1] == "mov" and t[2][1].startswith("#"):
                        v = int(t[2][1].lstrip("#"), 0) & 0xFFFFFFFFFFFFFFFF
                    elif t[1] == "movk" and v is not None:
                        sh = int(t[2][2].split("#")[1]) if len(t[2]) > 2 else 0
                        v = (v & ~(0xFFFF << sh)) | (int(t[2][1].lstrip("#"), 0) << sh)
                    else:
                        v = None
                return v

            def bound(idx):
                names = reg_names(idx)
                t = last(lambda t: t[1] == "cmp" and t[2][0] in names)
                if t is None:       # the index is often a copy of the register that was compared
                    mv = last(lambda t: t[1] == "mov" and t[2][0] in names and re.fullmatch(r"[xw]\d+", t[2][1]))
                    if mv:
                        names = reg_names(mv[2][1])
                        t = last(lambda t: t[1] == "cmp" and t[2][0] in names)
                if t is None:
                    return self.jt_fail(i.address)
                if t[2][1].startswith("#"):
                    v = int(t[2][1].lstrip("#"), 0)
                    if len(t[2]) > 2 and t[2][2].startswith("lsl"):
                        v <<= int(t[2][2].split("#")[1])
                    return v + 1
                if re.fullmatch(r"[xw]\d+", t[2][1]):
                    v = reg_const(t[2][1], t[0])
                    return v + 1 if v is not None else None
                return self.jt_fail(i.address)

            if len(o) == 4 and o[3] == "lsl #2":            # byte or halfword entries
                base = const_of(o[1])
                ld = last(lambda t: t[1] in ("ldrb", "ldrh") and t[2][0] == "w" + o[2][1:])
                if base is None or ld is None:
                    return self.jt_fail(i.address)
                m = re.fullmatch(r"\[(x\d+), ([xw]\d+)(?:, (?:lsl|uxtw) #1)?\]", ld[2][1])
                if not m:
                    return self.jt_fail(i.address)
                table, n = const_of(m.group(1)), bound(m.group(2))
                if table is None or (n is not None and n > 70000):
                    return self.jt_fail(i.address)
                size = 1 if ld[1] == "ldrb" else 2
                if n is None:
                    # the bound check is somewhere this scan does not see: take entries for as long as they land
                    # on a possible target. Reading too far only adds labels; stopping short is caught at run
                    # time, where an unlisted target traps.
                    for e in range(4096):
                        t = base + 4 * int.from_bytes(img.read(table + e * size, size), "little")
                        if not (self.start <= t < self.end) or (t not in self.leaders and t not in out):
                            break
                        out.add(t)
                    if not out:
                        return self.jt_fail(i.address)
                    continue
                for e in range(n):
                    v = int.from_bytes(img.read(table + e * size, size), "little")
                    out.add(base + 4 * v)
            elif len(o) == 3:                                 # 32-bit entries
                ld = last(lambda t: t[1] == "ldrsw" and t[2][0] in (o[1], o[2]))
                if ld is None:
                    return self.jt_fail(i.address)
                base_reg = o[2] if ld[2][0] == o[1] else o[1]
                m = re.fullmatch(r"\[(x\d+), ([xw]\d+), (?:lsl|uxtw|sxtw) #2\]", ld[2][1])
                if not m:
                    return self.jt_fail(i.address)
                table, n = const_of(m.group(1)), bound(m.group(2))
                base = table if base_reg == m.group(1) else const_of(base_reg)
                if table is None or n is None or base is None or n > 70000:
                    return self.jt_fail(i.address)
                for e in range(n):
                    out.add((base + struct.unpack("<i", img.read(table + 4 * e, 4))[0]) & U64)
            else:
                return self.jt_fail(i.address)
        if any(not (self.start <= t < self.end) or t % 4 for t in out):
            return None
        return out

    def jt_fail(self, addr):
        self.tr.jt_failures.append(addr)
        return None

    def render(self):
        body = "\n".join(self.lines)
        xs = sorted({int(m) for m in re.findall(r"\bx(\d+)\b", body)})
        vs = sorted({int(m) for m in re.findall(r"\bv(\d+)\b", body)})
        head = ["void F_%d_%x(cpu_t *c) {" % (self.img.index, self.start)]
        if xs:
            head.append("  uint64_t " + ", ".join(
                "x%d = %s" % (n, "c->x[%d]" % n if n <= 8 or n == 18 else "0") for n in xs) + ";")
        if vs:
            head.append("  V " + ", ".join("v%d" % n for n in vs) + ";")
            for n in vs:
                head.append("  v%d = %s;" % (n, "c->v[%d]" % n if n <= 7 else "VZERO"))
        head.append("  uint64_t sp = c->sp; uint32_t nf = 0, zf = 0, cf = 0, vf = 0; (void)nf; (void)zf; (void)cf; (void)vf; (void)sp;")
        so = " ".join(["c->x[%d] = x%d;" % (n, n) for n in xs if n <= 8 or n == 18] +
                      ["c->v[%d] = v%d;" % (n, n) for n in vs if n <= 7] + ["c->sp = sp;"])
        si = " ".join(["x%d = c->x[%d];" % (n, n) for n in xs if n <= 1] + ["v%d = c->v[%d];" % (n, n) for n in vs if n <= 3])
        ro = " ".join(["c->x[%d] = x%d;" % (n, n) for n in xs if n <= 1] + ["c->v[%d] = v%d;" % (n, n) for n in vs if n <= 3])
        # the register traffic at calls and the jump-table cases are macros, to keep the text small
        defs = ["#define SO do { %s } while (0)" % so, "#define SI do { %s } while (0)" % si,
                "#define RO do { %s } while (0)" % ro]
        if self.has_br:
            where = self.br_cases if self.br_cases is not None else range(self.start, self.end, 4)
            cases = " ".join("case 0x%xULL: goto %s;" % (a, self.label(a)) for a in where)
            defs.append("#define BRSWITCH %s" % cases)
        undefs = "#undef SO\n#undef SI\n#undef RO\n" + ("#undef BRSWITCH\n" if self.has_br else "")
        return "\n".join(defs) + "\n" + "\n".join(head) + "\n" + body + "\n}\n" + undefs

    # ---- one instruction -> list of C statements
    def insn(self, m, o, addr, raw):
        g, setg = self.g, self.setg
        IMG = "IMG%d" % self.img.index

        if m in ("nop", "paciasp", "autiasp", "bti", "prfm", "dmb", "hint", "xpaclri", "pacibsp", "autibsp", "yield", "isb", "clrex", "autia1716", "autib1716", "pacia1716", "pacib1716"):
            return ["/* %s */;" % m]

        # ------------------------------------------------------------------ branches
        if m == "b" or m == "bl":
            t = o[0].v
            if m == "b" and self.start <= t < self.end:
                return ["goto %s;" % self.label(t)]
            if m == "b" and t not in self.img.funcs and not (self.img.plt[0] <= t < self.img.plt[1]):
                # a linker veneer (the Cortex-A53 erratum 843419 fix): one instruction moved out of line,
                # followed by a branch back to the next instruction. Put the instruction back.
                v = list(self.img.md.disasm(self.img.read(t, 8), t))
                if len(v) == 2 and v[1].mnemonic == "b" and int(v[1].op_str.lstrip("#"), 0) == addr + 4:
                    return self.insn(v[0].mnemonic, [parse_op(x) for x in split_ops(v[0].op_str)], addr, v[0])
            call = self.call_target(t)
            if m == "bl":
                return ["SO; %s SI;" % call]
            return ["SO; %s return;" % call]
        if m.startswith("b."):
            c = m[2:]
            t = o[0].v
            if self.start <= t < self.end:
                return ["if (%s) goto %s;" % (CONDS[c], self.label(t))]
            return ["if (%s) { SO; %s return; }" % (CONDS[c], self.call_target(t))]
        if m in ("cbz", "cbnz"):
            return ["if (%s %s 0) goto %s;" % (g(o[0]), "==" if m == "cbz" else "!=", self.jump(o[1].v))]
        if m in ("tbz", "tbnz"):
            raw_reg = "x%d" % o[0].n if o[0].kind == "g" else "0"
            return ["if (((%s >> %d) & 1) %s 0) goto %s;" % (raw_reg, o[1].v, "==" if m == "tbz" else "!=", self.jump(o[2].v))]
        if m == "ret":
            return ["RO; return;"]
        if m == "blr":
            return ["SO; a2c_call(c, %s); SI;" % g(o[0])]
        if m == "br":
            return ["{ uint64_t t_ = %s; switch (t_ - %s) { BRSWITCH default: SO; a2c_call(c, t_); return; } }" % (g(o[0]), IMG)]
        if m in ("brk", "udf"):
            return ["a2c_trap(c, 0x%xULL, \"brk\");" % addr]

        # ------------------------------------------------------------------ addresses and moves
        if m in ("adr", "adrp"):
            return [setg(o[0], "%s + 0x%xULL" % (IMG, o[1].v))]
        if m == "mrs":
            return [setg(o[0], "a2c_mrs(c, \"%s\")" % o[1].name)]
        if m == "msr":
            return ["a2c_msr(c, \"%s\", %s);" % (o[0].name, g(o[1]))]
        if m == "movk":
            sh = o[2].amt if len(o) > 2 else 0
            w = o[0].w
            return [setg(o[0], "(%s & ~((%s)0xffff << %d)) | ((%s)%s << %d)" % (g(o[0]), UT[w], sh, UT[w], self.imm(o[1].v, w), sh))]
        if m in ("movz", "movn"):
            w = o[0].w
            v = o[1].v << (o[2].amt if len(o) > 2 else 0)
            return [setg(o[0], self.imm(v if m == "movz" else ~v, w))]

        if m == "mov":
            d, s = o[0], o[1]
            if d.kind in ("g", "sp", "zr") and s.kind in ("g", "sp", "zr", "imm"):
                return [setg(d, self.imm(s.v, d.w) if s.kind == "imm" else g(s))]
            if d.kind in ("g",) and s.kind == "ve":           # umov
                return [setg(d, "v%d.%s[%d]" % (s.n, FLD[s.es], s.idx))]
            if d.kind == "ve" and s.kind in ("g", "zr"):      # ins from general
                return ["v%d.%s[%d] = (%s)%s;" % (d.n, FLD[d.es], d.idx, UT[d.es], g(s))]
            if d.kind == "ve" and s.kind == "ve":             # ins element
                return ["v%d.%s[%d] = v%d.%s[%d];" % (d.n, FLD[d.es], d.idx, s.n, FLD[s.es], s.idx)]
            if d.kind == "fs" and s.kind == "ve":             # dup scalar
                return [self.setbits(d, "v%d.%s[%d]" % (s.n, FLD[s.es], s.idx))]
            if d.kind == "v" and s.kind == "v":
                if d.cnt * d.es == 128:
                    return ["v%d = v%d;" % (d.n, s.n)]
                return ["{ V t; t.q[0] = v%d.q[0]; t.q[1] = 0; v%d = t; }" % (s.n, d.n)]
            raise Unsupported("mov form")
        if m in ("umov", "smov"):
            d, s = o[0], o[1]
            if m == "umov":
                return [setg(d, "v%d.%s[%d]" % (s.n, FLD[s.es], s.idx))]
            return [setg(d, "(%s)v%d.%s[%d]" % (ST[d.w], s.n, SFLD[s.es], s.idx))]
        if m == "ins":
            d, s = o[0], o[1]
            if s.kind == "ve":
                return ["v%d.%s[%d] = v%d.%s[%d];" % (d.n, FLD[d.es], d.idx, s.n, FLD[s.es], s.idx)]
            return ["v%d.%s[%d] = (%s)%s;" % (d.n, FLD[d.es], d.idx, UT[d.es], g(s))]

        # ------------------------------------------------------------------ integer arithmetic and logic
        if m in ("add", "sub", "adds", "subs", "cmp", "cmn", "neg", "negs") and o[0].kind in ("g", "sp", "zr"):
            if m in ("cmp", "cmn"):
                w = o[0].w
                a, b = "(%s)%s" % (UT[w], g(o[0])), self.op2(o[1:], w)
                f = self.flags_sub if m == "cmp" else self.flags_add
                return [f(a, b, w).replace("RES", "")]
            if m in ("neg", "negs"):
                w = o[0].w
                b = self.op2(o[1:], w)
                if m == "neg":
                    return [setg(o[0], "(%s)0 - %s" % (UT[w], b))]
                return [self.flags_sub("0", b, w).replace("RES", setg(o[0], "r_"))]
            w = o[0].w
            a, b = "(%s)%s" % (UT[w], g(o[1])), self.op2(o[2:], w)
            if m == "add":
                return [setg(o[0], "%s + %s" % (a, b))]
            if m == "sub":
                return [setg(o[0], "%s - %s" % (a, b))]
            f = self.flags_sub if m == "subs" else self.flags_add
            return [f(a, b, w).replace("RES", setg(o[0], "r_"))]
        if m in ("adc", "adcs", "sbc", "sbcs", "ngc", "ngcs"):
            w = o[0].w
            if m.startswith("ngc"):
                a, b = "(%s)0" % UT[w], "(%s)%s" % (UT[w], g(o[1]))
            else:
                a, b = "(%s)%s" % (UT[w], g(o[1])), "(%s)%s" % (UT[w], g(o[2]))
            if m.startswith("sbc") or m.startswith("ngc"):
                b = "(%s)~%s" % (UT[w], b)
            if not m.endswith("s"):
                return [setg(o[0], "%s + %s + cf" % (a, b))]
            return ["{ %s a_ = %s, b_ = %s; %s r_ = a_ + b_ + cf; uint32_t c_ = (r_ < a_) || (cf && r_ == a_); "
                    "nf = r_ >> %d; zf = r_ == 0; vf = (~(a_ ^ b_) & (a_ ^ r_)) >> %d; cf = c_; %s }"
                    % (UT[w], a, b, UT[w], w - 1, w - 1, setg(o[0], "r_"))]
        if m in ("and", "orr", "eor", "bic", "orn", "eon", "ands", "bics", "tst") and o[0].kind in ("g", "sp", "zr"):
            if m == "tst":
                w = o[0].w
                return ["{ %s r_ = (%s)%s & %s; nf = r_ >> %d; zf = r_ == 0; cf = 0; vf = 0; }" % (UT[w], UT[w], g(o[0]), self.op2(o[1:], w), w - 1)]
            w = o[0].w
            a, b = "(%s)%s" % (UT[w], g(o[1])), self.op2(o[2:], w)
            cop = {"and": "&", "ands": "&", "orr": "|", "eor": "^", "bic": "& ~", "bics": "& ~", "orn": "| ~", "eon": "^ ~"}[m]
            e = "%s %s%s" % (a, cop, b)
            if m in ("ands", "bics"):
                return ["{ %s r_ = %s; nf = r_ >> %d; zf = r_ == 0; cf = 0; vf = 0; %s }" % (UT[w], e, w - 1, setg(o[0], "r_"))]
            return [setg(o[0], e)]
        if m == "mvn" and o[0].kind in ("g", "zr"):
            return [setg(o[0], "~%s" % self.op2(o[1:], o[0].w))]
        if m in ("lsl", "lsr", "asr", "ror") and o[0].kind in ("g", "zr"):
            w = o[0].w
            a = "(%s)%s" % (UT[w], g(o[1]))
            sh = "%d" % (o[2].v & (w - 1)) if o[2].kind == "imm" else "(%s & %d)" % (g(o[2]), w - 1)
            if m == "lsl":
                return [setg(o[0], "%s << %s" % (a, sh))]
            if m == "lsr":
                return [setg(o[0], "%s >> %s" % (a, sh))]
            if m == "asr":
                return [setg(o[0], "(%s)((%s)%s >> %s)" % (UT[w], ST[w], a, sh))]
            return [setg(o[0], "ror%d(%s, %s)" % (w, a, sh))]
        if m in ("mul", "madd", "msub", "mneg"):
            w = o[0].w
            a, b = "(%s)%s" % (UT[w], g(o[1])), "(%s)%s" % (UT[w], g(o[2]))
            if m == "mul":
                return [setg(o[0], "%s * %s" % (a, b))]
            if m == "mneg":
                return [setg(o[0], "(%s)0 - %s * %s" % (UT[w], a, b))]
            c3 = "(%s)%s" % (UT[w], g(o[3]))
            return [setg(o[0], "%s %s %s * %s" % (c3, "+" if m == "madd" else "-", a, b))]
        if m in ("smull", "umull", "smaddl", "umaddl", "smsubl", "umsubl", "smnegl", "umnegl") and o[0].kind in ("g", "zr"):
            s = m[0] == "s"
            cast = "(int64_t)(int32_t)" if s else "(uint64_t)(uint32_t)"
            p = "(uint64_t)(%sx%d * %sx%d)" % (cast, o[1].n, cast, o[2].n) if o[1].kind == "g" and o[2].kind == "g" else "0"
            if m.endswith("mull"):
                return [setg(o[0], p)]
            if m.endswith("mnegl"):
                return [setg(o[0], "0 - %s" % p)]
            return [setg(o[0], "%s %s %s" % (g(o[3]), "+" if "madd" in m else "-", p))]
        if m in ("smulh", "umulh"):
            return [setg(o[0], "%s(%s, %s)" % (m, g(o[1]), g(o[2])))]
        if m in ("sdiv", "udiv"):
            w = o[0].w
            return [setg(o[0], "%s%d(%s, %s)" % (m, w, g(o[1]), g(o[2])))]
        if m in ("sxtb", "sxth", "sxtw", "uxtb", "uxth", "uxtw") and o[0].kind in ("g", "zr"):
            src = {"b": 8, "h": 16, "w": 32}[m[3]]
            raw_reg = "x%d" % o[1].n if o[1].kind == "g" else "0"
            if m[0] == "s":
                return [setg(o[0], "(%s)(%s)%s" % (ST[o[0].w], ST[src], raw_reg))]
            return [setg(o[0], "(%s)%s" % (UT[src], raw_reg))]
        if m in ("ubfx", "sbfx", "ubfiz", "sbfiz", "bfi", "bfxil", "bfc"):
            w = o[0].w
            if m == "bfc":
                lsb, wid = o[1].v, o[2].v
                mask = ((1 << wid) - 1) << lsb
                return [setg(o[0], "%s & ~%s" % (g(o[0]), self.imm(mask, w)))]
            src = "(%s)%s" % (UT[w], g(o[1]))
            lsb, wid = o[2].v, o[3].v
            mask = (1 << wid) - 1
            if m == "ubfx":
                return [setg(o[0], "(%s >> %d) & %s" % (src, lsb, self.imm(mask, w)))]
            if m == "sbfx":
                return [setg(o[0], "(%s)((%s)(%s << %d) >> %d)" % (UT[w], ST[w], src, w - lsb - wid, w - wid))]
            if m == "ubfiz":
                return [setg(o[0], "(%s & %s) << %d" % (src, self.imm(mask, w), lsb))]
            if m == "sbfiz":
                return [setg(o[0], "(%s)((%s)(%s << %d) >> %d)" % (UT[w], ST[w], src, w - wid, w - wid - lsb))]
            if m == "bfi":
                return [setg(o[0], "(%s & ~%s) | ((%s & %s) << %d)" % (g(o[0]), self.imm(mask << lsb, w), src, self.imm(mask, w), lsb))]
            return [setg(o[0], "(%s & ~%s) | ((%s >> %d) & %s)" % (g(o[0]), self.imm(mask, w), src, lsb, self.imm(mask, w)))]
        if m == "extr":
            w = o[0].w
            lsb = o[3].v
            if lsb == 0:
                return [setg(o[0], g(o[2]))]
            return [setg(o[0], "((%s)%s >> %d) | ((%s)%s << %d)" % (UT[w], g(o[2]), lsb, UT[w], g(o[1]), w - lsb))]
        if m in ("clz", "cls", "rbit", "rev", "rev16", "rev32") and o[0].kind in ("g", "zr"):
            return [setg(o[0], "%s%d(%s)" % (m, o[0].w, g(o[1])))]
        if m in ("csel", "csinc", "csinv", "csneg"):
            w = o[0].w
            a, b = "(%s)%s" % (UT[w], g(o[1])), "(%s)%s" % (UT[w], g(o[2]))
            alt = {"csel": b, "csinc": "%s + 1" % b, "csinv": "~%s" % b, "csneg": "(%s)0 - %s" % (UT[w], b)}[m]
            return [setg(o[0], "%s ? %s : %s" % (CONDS[o[3].c], a, alt))]
        if m in ("cset", "csetm"):
            return [setg(o[0], "%s ? %s : 0" % (CONDS[o[1].c], "1" if m == "cset" else self.imm(-1, o[0].w)))]
        if m in ("cinc", "cinv", "cneg"):
            w = o[0].w
            a = "(%s)%s" % (UT[w], g(o[1]))
            alt = {"cinc": "%s + 1" % a, "cinv": "~%s" % a, "cneg": "(%s)0 - %s" % (UT[w], a)}[m]
            return [setg(o[0], "%s ? %s : %s" % (CONDS[o[2].c], alt, a))]
        if m in ("ccmp", "ccmn"):
            w = o[0].w
            a = "(%s)%s" % (UT[w], g(o[0]))
            b = self.imm(o[1].v, w) if o[1].kind == "imm" else "(%s)%s" % (UT[w], g(o[1]))
            f = (self.flags_sub if m == "ccmp" else self.flags_add)(a, b, w).replace("RES", "")
            return ["if (%s) %s else { %s }" % (CONDS[o[3].c], f, self.nzcv(o[2].v))]

        # ------------------------------------------------------------------ loads and stores
        LD = {"ldr": None, "ldur": None, "ldrb": (8, 0), "ldurb": (8, 0), "ldrh": (16, 0), "ldurh": (16, 0),
              "ldrsb": (8, 1), "ldursb": (8, 1), "ldrsh": (16, 1), "ldursh": (16, 1), "ldrsw": (32, 1), "ldursw": (32, 1),
              "ldar": None, "ldarb": (8, 0), "ldarh": (16, 0), "ldxr": None, "ldaxr": None, "ldxrb": (8, 0), "ldaxrb": (8, 0),
              "ldxrh": (16, 0), "ldaxrh": (16, 0)}
        if m in LD:
            d = o[0]
            a, pre, post = self.mem_access(o, 1)
            spec = LD[m]
            if d.kind == "fs":
                n = d.w
                if n == 128:
                    st = "v%d.i = ldq(%s);" % (d.n, a)
                else:
                    st = "v%d = mk_%s(ld%d(%s));" % (d.n, FLD[n], n, a)
            elif spec is None:
                st = setg(d, "ld%d(%s)" % (d.w, a))
            else:
                size, signed = spec
                st = setg(d, "(%s)(%s)ld%d(%s)" % (ST[d.w], ST[size], size, a) if signed else "ld%d(%s)" % (size, a))
            return [x for x in (pre, st, post) if x]
        ST_ = {"str": None, "stur": None, "strb": 8, "sturb": 8, "strh": 16, "sturh": 16, "stlr": None, "stlrb": 8, "stlrh": 16}
        if m in ST_:
            d = o[0]
            a, pre, post = self.mem_access(o, 1)
            if d.kind == "fs":
                if d.w == 128:
                    st = "stq(%s, v%d.i);" % (a, d.n)
                else:
                    st = "st%d(%s, v%d.%s[0]);" % (d.w, a, d.n, FLD[d.w])
            else:
                size = ST_[m] or d.w
                st = "st%d(%s, (%s)%s);" % (size, a, UT[size], g(d))
            # the value is read before a pre-index update only matters when the stored register is the base
            if pre and d.kind == "g" and o[1].base.kind == "g" and d.n == o[1].base.n:
                return ["{ uint64_t v_ = %s; %s st%d(%s, (%s)v_); }" % (g(d), pre, ST_[m] or d.w, a, UT[ST_[m] or d.w])]
            return [x for x in (pre, st, post) if x]
        if m in ("stxr", "stlxr", "stxrb", "stlxrb", "stxrh", "stlxrh"):
            size = 8 if m.endswith("b") else 16 if m.endswith("h") else o[1].w
            a, pre, post = self.mem_access(o, 2)
            return ["st%d(%s, (%s)%s);" % (size, a, UT[size], g(o[1])), setg(o[0], "0")]
        if m in ("ldp", "ldpsw", "stp"):
            a_, b_ = o[0], o[1]
            a, pre, post = self.mem_access(o, 2)
            n = a_.w
            step = n // 8 if m != "ldpsw" else 4
            out = [pre] if pre else []
            if m == "stp":
                if a_.kind == "fs":
                    for k, r in enumerate((a_, b_)):
                        if n == 128:
                            out.append("stq(%s + %d, v%d.i);" % (a, k * 16, r.n))
                        else:
                            out.append("st%d(%s + %d, v%d.%s[0]);" % (n, a, k * step, r.n, FLD[n]))
                else:
                    out.append("st%d(%s, (%s)%s); st%d(%s + %d, (%s)%s);" % (n, a, UT[n], g(a_), n, a, step, UT[n], g(b_)))
            elif a_.kind == "fs":
                if n == 128:
                    out.append("{ __m128i t0 = ldq(%s), t1 = ldq(%s + 16); v%d.i = t0; v%d.i = t1; }" % (a, a, a_.n, b_.n))
                else:
                    out.append("{ %s t0 = ld%d(%s), t1 = ld%d(%s + %d); v%d = mk_%s(t0); v%d = mk_%s(t1); }" % (UT[n], n, a, n, a, step, a_.n, FLD[n], b_.n, FLD[n]))
            elif m == "ldpsw":
                out.append("{ uint64_t t0 = (int64_t)(int32_t)ld32(%s), t1 = (int64_t)(int32_t)ld32(%s + 4); %s %s }" % (a, a, setg(a_, "t0"), setg(b_, "t1")))
            else:
                out.append("{ %s t0 = ld%d(%s), t1 = ld%d(%s + %d); %s %s }" % (UT[n], n, a, n, a, step, setg(a_, "t0"), setg(b_, "t1")))
            if post:
                out.append(post)
            return out

        # ------------------------------------------------------------------ everything fp and simd
        return self.simd(m, o, addr)

    def jump(self, t):
        if self.start <= t < self.end:
            return self.label(t)
        raise Unsupported("conditional branch out of the function to %x" % t)

    # ---- fp / simd
    def sse(self, m, o):
        """SSE form of the common whole-register operations, or None. Lanes above the operand's width are cleared,
        as arm64 does."""
        d = o[0]
        if d.kind != "v":
            return None
        n = d.n
        full = d.cnt * d.es == 128

        def low(e):      # result expression (an __m128i) cut to the destination's width
            return e if full else "A2C_LOW64(%s)" % e

        def ps(x):       # operand as __m128, an element operand broadcast
            if x.kind == "ve":
                return "_mm_shuffle_ps(v%d.m, v%d.m, %d)" % (x.n, x.n, x.idx * 0x55)
            return "v%d.m" % x.n

        def pd(x):
            if x.kind == "ve":
                return "_mm_shuffle_pd(v%d.md, v%d.md, %d)" % (x.n, x.n, x.idx * 3)
            return "v%d.md" % x.n

        if m in ("fadd", "fsub", "fmul", "fdiv") and d.es in (32, 64):
            op = {"fadd": "add", "fsub": "sub", "fmul": "mul", "fdiv": "div"}[m]
            if d.es == 32:
                return ["v%d.i = %s;" % (n, low("_mm_castps_si128(_mm_%s_ps(%s, %s))" % (op, ps(o[1]), ps(o[2]))))]
            return ["v%d.md = _mm_%s_pd(%s, %s);" % (n, op, pd(o[1]), pd(o[2]))]
        if m in ("fmla", "fmls") and d.es in (32, 64):
            fn = "fmadd" if m == "fmla" else "fnmadd"
            if d.es == 32:
                return ["v%d.i = %s;" % (n, low("_mm_castps_si128(_mm_%s_ps(%s, %s, v%d.m))" % (fn, ps(o[1]), ps(o[2]), n)))]
            return ["v%d.md = _mm_%s_pd(%s, %s, v%d.md);" % (n, fn, pd(o[1]), pd(o[2]), n)]
        if m in ("fmax", "fmin", "fmaxnm", "fminnm") and d.es == 32:
            return ["v%d.i = %s;" % (n, low("_mm_castps_si128(%s4(%s, %s))" % (m, ps(o[1]), ps(o[2]))))]
        if m == "frecpe" and d.es == 32 and full:
            return ["v%d.m = frecpe4(v%d.m);" % (n, o[1].n)]
        if m == "fabs" and d.es == 32:
            return ["v%d.i = %s;" % (n, low("_mm_and_si128(v%d.i, _mm_set1_epi32(0x7fffffff))" % o[1].n))]
        if m == "fneg" and d.es == 32:
            return ["v%d.i = %s;" % (n, low("_mm_xor_si128(v%d.i, _mm_set1_epi32((int)0x80000000u))" % o[1].n))]
        if m == "fsqrt" and d.es == 32 and full:
            return ["v%d.m = _mm_sqrt_ps(v%d.m);" % (n, o[1].n)]
        if m == "faddp" and d.es == 32 and len(o) == 3:
            h = "_mm_hadd_ps(v%d.m, v%d.m)" % (o[1].n, o[2].n)
            if full:
                return ["v%d.m = %s;" % (n, h)]
            return ["{ __m128 h_ = %s; v%d.i = A2C_LOW64(_mm_castps_si128(_mm_shuffle_ps(h_, h_, 0x08))); }" % (h, n)]
        if m in ("and", "orr", "eor") and len(o) == 3 and o[2].kind == "v":
            op = {"and": "and", "orr": "or", "eor": "xor"}[m]
            return ["v%d.i = %s;" % (n, low("_mm_%s_si128(v%d.i, v%d.i)" % (op, o[1].n, o[2].n)))]
        if m == "bic" and len(o) == 3 and o[2].kind == "v":
            return ["v%d.i = %s;" % (n, low("_mm_andnot_si128(v%d.i, v%d.i)" % (o[2].n, o[1].n)))]
        if m in ("bsl", "bit", "bif"):
            D, N, M = "v%d.i" % n, "v%d.i" % o[1].n, "v%d.i" % o[2].n
            e = {"bsl": "_mm_or_si128(_mm_and_si128({D}, {N}), _mm_andnot_si128({D}, {M}))",
                 "bit": "_mm_or_si128(_mm_andnot_si128({M}, {D}), _mm_and_si128({N}, {M}))",
                 "bif": "_mm_or_si128(_mm_and_si128({D}, {M}), _mm_andnot_si128({M}, {N}))"}[m].format(D=D, N=N, M=M)
            return ["v%d.i = %s;" % (n, low(e))]
        if m == "mov" and o[1].kind == "v":
            return ["v%d.i = %s;" % (n, low("v%d.i" % o[1].n))]
        if m == "movi" and o[1].v == 0 and len(o) == 2:
            return ["v%d.i = _mm_setzero_si128();" % n]
        if m == "dup" and d.es == 32 and full:
            if o[1].kind == "ve" and o[1].es == 32:
                return ["v%d.m = _mm_shuffle_ps(v%d.m, v%d.m, %d);" % (n, o[1].n, o[1].n, o[1].idx * 0x55)]
            if o[1].kind in ("g", "zr"):
                return ["v%d.i = _mm_set1_epi32((int)%s);" % (n, self.g(o[1]))]
        if m == "dup" and d.es == 64 and full and o[1].kind == "ve" and o[1].es == 64:
            return ["v%d.md = _mm_shuffle_pd(v%d.md, v%d.md, %d);" % (n, o[1].n, o[1].n, o[1].idx * 3)]
        if m == "ext" and full and d.es == 8:
            return ["v%d.i = _mm_alignr_epi8(v%d.i, v%d.i, %d);" % (n, o[2].n, o[1].n, o[3].v)]
        if m == "scvtf" and d.es == 32 and full and len(o) == 2:
            return ["v%d.m = _mm_cvtepi32_ps(v%d.i);" % (n, o[1].n)]
        if m in ("fcmeq", "fcmge", "fcmgt") and d.es == 32:
            pred = {"fcmeq": "_CMP_EQ_OQ", "fcmge": "_CMP_GE_OQ", "fcmgt": "_CMP_GT_OQ"}[m]
            b = "_mm_setzero_ps()" if o[2].kind == "imm" else ps(o[2])
            return ["v%d.i = %s;" % (n, low("_mm_castps_si128(_mm_cmp_ps(%s, %s, %s))" % (ps(o[1]), b, pred)))]
        if m in ("add", "sub") and d.es in (8, 16, 32, 64) and len(o) == 3 and o[2].kind == "v":
            return ["v%d.i = %s;" % (n, low("_mm_%s_epi%d(v%d.i, v%d.i)" % (m, d.es, o[1].n, o[2].n)))]
        return None

    def simd(self, m, o, addr):
        g, setg = self.g, self.setg
        d = o[0]
        fast = self.sse(m, o)
        if fast is not None:
            return fast
        if m == "ld1r" and len(o[0].regs) == 1 and o[0].regs[0].kind == "v" and o[0].regs[0].es == 32 and o[0].regs[0].cnt == 4:
            a, pre, post = self.mem_access(o, 1)
            out = ["v%d.i = _mm_set1_epi32((int)ld32(%s));" % (o[0].regs[0].n, a)]
            if len(o) > 2:
                base = "sp" if o[1].base.kind == "sp" else "x%d" % o[1].base.n
                out.append("%s += %s;" % (base, self.imm(o[2].v, 64) if o[2].kind == "imm" else "x%d" % o[2].n))
            return out

        # ---- structure loads/stores
        if m in ("ld1", "ld2", "ld3", "ld4", "st1", "st2", "st3", "st4", "ld1r", "ld2r", "ld3r", "ld4r"):
            regs = o[0].regs
            a, pre, post = self.mem_access(o, 1)
            n = len(regs)
            out = []
            r0 = regs[0]
            if r0.kind == "ve":          # single element form
                es = r0.es
                for k, r in enumerate(regs):
                    if m.startswith("ld"):
                        out.append("v%d.%s[%d] = ld%d(%s + %d);" % (r.n, FLD[es], r.idx, es, a, k * es // 8))
                    else:
                        out.append("st%d(%s + %d, v%d.%s[%d]);" % (es, a, k * es // 8, r.n, FLD[es], r.idx))
                total = n * es // 8
            elif m.endswith("r"):
                es, cnt = r0.es, r0.cnt
                for k, r in enumerate(regs):
                    out.append("{ %s e_ = ld%d(%s + %d); V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) t.%s[i] = e_; v%d = t; }"
                               % (UT[es], es, a, k * es // 8, cnt, FLD[es], r.n))
                total = n * es // 8
            else:
                es, cnt = r0.es, r0.cnt
                interleaved = int(m[2]) > 1
                tmp = ["t%d" % k for k in range(n)]
                if m.startswith("ld"):
                    s = "{ V %s; " % ", ".join(tmp)
                    s += " ".join("%s.q[0] = %s.q[1] = 0;" % (t, t) for t in tmp)
                    if interleaved:
                        s += " for (int i = 0; i < %d; i++) { %s }" % (cnt, " ".join(
                            "t%d.%s[i] = ld%d(%s + (i * %d + %d) * %d);" % (k, FLD[es], es, a, n, k, es // 8) for k in range(n)))
                    else:
                        s += " " + " ".join("for (int i = 0; i < %d; i++) t%d.%s[i] = ld%d(%s + %d + i * %d);"
                                            % (cnt, k, FLD[es], es, a, k * cnt * es // 8, es // 8) for k in range(n))
                    s += " " + " ".join("v%d = t%d;" % (r.n, k) for k, r in enumerate(regs)) + " }"
                    out.append(s)
                else:
                    if interleaved:
                        out.append("for (int i = 0; i < %d; i++) { %s }" % (cnt, " ".join(
                            "st%d(%s + (i * %d + %d) * %d, v%d.%s[i]);" % (es, a, n, k, es // 8, r.n, FLD[es]) for k, r in enumerate(regs))))
                    else:
                        for k, r in enumerate(regs):
                            out.append("for (int i = 0; i < %d; i++) st%d(%s + %d + i * %d, v%d.%s[i]);"
                                       % (cnt, es, a, k * cnt * es // 8, es // 8, r.n, FLD[es]))
                total = n * cnt * es // 8
            if len(o) > 2:
                base = "sp" if o[1].base.kind == "sp" else "x%d" % o[1].base.n
                out.append("%s += %s;" % (base, self.imm(o[2].v, 64) if o[2].kind == "imm" else "x%d" % o[2].n))
            return out

        # ---- fmov
        if m == "fmov":
            s = o[1]
            if d.kind == "fs" and s.kind == "imm":
                return [self.setfs(d, repr(float(s.v)) + ("f" if d.w == 32 else ""))]
            if d.kind == "fs" and s.kind == "fs":
                return [self.setbits(d, self.fsbits(s))]
            if d.kind == "fs" and s.kind in ("g", "zr"):
                return [self.setbits(d, "(%s)%s" % (UT[d.w], g(s)))]
            if d.kind in ("g", "zr") and s.kind == "fs":
                return [setg(d, self.fsbits(s))]
            if d.kind in ("g", "zr") and s.kind == "ve":
                return [setg(d, "v%d.q[%d]" % (s.n, s.idx))]
            if d.kind == "ve":
                return ["v%d.q[%d] = %s;" % (d.n, d.idx, g(s))]
            if d.kind == "v" and s.kind == "imm":
                return [self.vec(d, repr(float(s.v)) + ("f" if d.es == 32 else ""), fld=FFLD[d.es])]
            raise Unsupported("fmov form")

        # ---- scalar/vector float arithmetic
        FB = {"fadd": "({a} + {b})", "fsub": "({a} - {b})", "fmul": "({a} * {b})", "fdiv": "({a} / {b})",
              "fnmul": "(-({a} * {b}))", "fmax": "fmax{w}({a}, {b})", "fmin": "fmin{w}({a}, {b})",
              "fmaxnm": "fmaxnm{w}({a}, {b})", "fminnm": "fminnm{w}({a}, {b})", "fabd": "fabs{w}({a} - {b})",
              "fmulx": "({a} * {b})"}
        if m in FB:
            if d.kind == "fs":
                e = FB[m].format(a=self.fsr(o[1]), b=self.fsr(o[2]), w=d.w)
                return [self.setfs(d, e)]
            if d.kind == "v":
                f = FFLD[d.es]
                e = FB[m].format(a=self.lane(o[1], f), b=self.lane(o[2], f), w=d.es)
                return [self.vec(d, e, fld=f)]
        FU = {"fabs": "fabs{w}({a})", "fneg": "(-{a})", "fsqrt": "sqrt{w}({a})", "frintm": "floor{w}({a})",
              "frintp": "ceil{w}({a})", "frintz": "trunc{w}({a})", "frinta": "round{w}({a})",
              "frintn": "roundeven{w}({a})", "frintx": "roundeven{w}({a})", "frinti": "roundeven{w}({a})",
              "frecpe": "frecpe{w}({a})", "frsqrte": "frsqrte{w}({a})"}
        if m in FU:
            if d.kind == "fs":
                return [self.setfs(d, FU[m].format(a=self.fsr(o[1]), w=d.w))]
            if d.kind == "v":
                f = FFLD[d.es]
                return [self.vec(d, FU[m].format(a=self.lane(o[1], f), w=d.es), fld=f)]
        if m in ("fmadd", "fmsub", "fnmadd", "fnmsub"):
            n_, m_, a_ = self.fsr(o[1]), self.fsr(o[2]), self.fsr(o[3])
            fn = "fmaf" if d.w == 32 else "fma"
            e = {"fmadd": "%s(%s, %s, %s)" % (fn, n_, m_, a_), "fmsub": "%s(-%s, %s, %s)" % (fn, n_, m_, a_),
                 "fnmadd": "%s(-%s, %s, -%s)" % (fn, n_, m_, a_), "fnmsub": "%s(%s, %s, -%s)" % (fn, n_, m_, a_)}[m]
            return [self.setfs(d, e)]
        if m in ("fmla", "fmls"):
            neg = "-" if m == "fmls" else ""
            if d.kind == "fs":
                fn = "fmaf" if d.w == 32 else "fma"
                return [self.setfs(d, "%s(%s%s, %s, %s)" % (fn, neg, self.fsr(o[1]), self.fsr(o[2]), self.fsr(d)))]
            f = FFLD[d.es]
            fn = "fmaf" if d.es == 32 else "fma"
            return [self.vec(d, "%s(%s%s, %s, v%d.%s[i])" % (fn, neg, self.lane(o[1], f), self.lane(o[2], f), d.n, f), fld=f)]
        if m in ("fcmp", "fcmpe"):
            b = "0" if o[1].kind == "imm" else self.fsr(o[1])
            return [self.fcmp(self.fsr(o[0]), b)]
        if m in ("fccmp", "fccmpe"):
            return ["if (%s) %s else { %s }" % (CONDS[o[3].c], self.fcmp(self.fsr(o[0]), self.fsr(o[1])), self.nzcv(o[2].v))]
        if m == "fcsel":
            return [self.setbits(d, "%s ? %s : %s" % (CONDS[o[3].c], self.fsbits(o[1]), self.fsbits(o[2])))]
        if m == "fcvt":
            s = o[1]
            if d.w == 16:
                return [self.setbits(d, "f%d_to_half(%s)" % (s.w, self.fsr(s)))]
            if s.w == 16:
                return [self.setfs(d, "(%s)half_to_f32(v%d.h[0])" % (FT[d.w], s.n))]
            return [self.setfs(d, "(%s)%s" % (FT[d.w], self.fsr(s)))]
        if m in ("scvtf", "ucvtf"):
            s = o[1]
            sg = m[0] == "s"
            if d.kind == "fs" and s.kind in ("g", "zr"):
                src = "(%s)%s" % ((ST if sg else UT)[s.w], g(s))
                e = "(%s)%s" % (FT[d.w], src)
                if len(o) > 2:
                    e = "(%s)((double)%s / %r)" % (FT[d.w], src, float(1 << o[2].v))
                return [self.setfs(d, e)]
            if d.kind == "fs" and s.kind == "fs":
                e = "(%s)v%d.%s[0]" % (FT[d.w], s.n, (SFLD if sg else FLD)[s.w])
                if len(o) > 2:
                    e = "(%s)((double)v%d.%s[0] / %r)" % (FT[d.w], s.n, (SFLD if sg else FLD)[s.w], float(1 << o[2].v))
                return [self.setfs(d, e)]
            if d.kind == "v":
                e = "(%s)v%d.%s[i]" % (FT[d.es], s.n, (SFLD if sg else FLD)[d.es])
                if len(o) > 2:
                    e = "(%s)((double)v%d.%s[i] / %r)" % (FT[d.es], s.n, (SFLD if sg else FLD)[d.es], float(1 << o[2].v))
                return [self.vec(d, e, fld=FFLD[d.es])]
        CV = {"fcvtzs": ("trunc", 1), "fcvtzu": ("trunc", 0), "fcvtms": ("floor", 1), "fcvtmu": ("floor", 0),
              "fcvtps": ("ceil", 1), "fcvtpu": ("ceil", 0), "fcvtas": ("round", 1), "fcvtau": ("round", 0),
              "fcvtns": ("roundeven", 1), "fcvtnu": ("roundeven", 0)}
        if m in CV:
            rnd, sg = CV[m]
            s = o[1]
            if d.kind in ("g", "zr"):
                src = "%s%d(%s)" % (rnd, s.w, self.fsr(s))
                if len(o) > 2:
                    src = "%s%d(%s * %r)" % (rnd, s.w, self.fsr(s), float(1 << o[2].v))
                return [setg(d, "f2%s%d(%s)" % ("s" if sg else "u", d.w, src))]
            if d.kind == "fs":
                src = "%s%d(%s)" % (rnd, s.w, self.fsr(s))
                return [self.setbits(d, "(%s)f2%s%d(%s)" % (UT[d.w], "s" if sg else "u", d.w, src))]
            if d.kind == "v":
                f = FFLD[d.es]
                src = "%s%d(v%d.%s[i])" % (rnd, d.es, s.n, f)
                if len(o) > 2:
                    src = "%s%d(v%d.%s[i] * %r)" % (rnd, d.es, s.n, f, float(1 << o[2].v))
                return [self.vec(d, "(%s)f2%s%d(%s)" % (UT[d.es], "s" if sg else "u", d.es, src))]
        if m in ("fcvtl", "fcvtl2"):
            s = o[1]
            hi = m.endswith("2")
            if d.es == 32:      # half -> single
                return [self.vec(d, "half_to_f32(v%d.h[i + %d])" % (s.n, 4 if hi else 0), fld="f")]
            return [self.vec(d, "(double)v%d.f[i + %d]" % (s.n, 2 if hi else 0), fld="d")]
        if m in ("fcvtn", "fcvtn2"):
            s = o[1]
            hi = m.endswith("2")
            if s.es == 32:      # single -> half
                e, fld, cnt, off = "f32_to_half(v%d.f[i])" % s.n, "h", 4, 4
            else:
                e, fld, cnt, off = "(float)v%d.d[i]" % s.n, "f", 2, 2
            if hi:
                return ["{ V t = v%d; for (int i = 0; i < %d; i++) t.%s[i + %d] = %s; v%d = t; }" % (d.n, cnt, fld, off, e, d.n)]
            return ["{ V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) t.%s[i] = %s; v%d = t; }" % (cnt, fld, e, d.n)]
        if m in ("faddp", "fmaxnmp", "fminnmp", "fmaxp", "fminp"):
            op = {"faddp": "({a} + {b})", "fmaxnmp": "fmaxnm{w}({a}, {b})", "fminnmp": "fminnm{w}({a}, {b})",
                  "fmaxp": "fmax{w}({a}, {b})", "fminp": "fmin{w}({a}, {b})"}[m]
            if d.kind == "fs":
                s = o[1]
                f = FFLD[s.es]
                return [self.setfs(d, op.format(a="v%d.%s[0]" % (s.n, f), b="v%d.%s[1]" % (s.n, f), w=s.es))]
            f = FFLD[d.es]
            h = d.cnt // 2
            a, b = o[1].n, o[2].n
            return ["{ V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) { t.%s[i] = %s; t.%s[i + %d] = %s; } v%d = t; }"
                    % (h, f, op.format(a="v%d.%s[2 * i]" % (a, f), b="v%d.%s[2 * i + 1]" % (a, f), w=d.es),
                       f, h, op.format(a="v%d.%s[2 * i]" % (b, f), b="v%d.%s[2 * i + 1]" % (b, f), w=d.es), d.n)]
        if m in ("fmaxnmv", "fminnmv", "fmaxv", "fminv"):
            s = o[1]
            fn = m[:-1] + "32"
            return [self.setfs(d, "%s(%s(v%d.f[0], v%d.f[1]), %s(v%d.f[2], v%d.f[3]))" % (fn, fn, s.n, s.n, fn, s.n, s.n))]
        FC = {"fcmeq": "==", "fcmge": ">=", "fcmgt": ">", "fcmle": "<=", "fcmlt": "<"}
        if m in FC or m in ("facge", "facgt"):
            if m in FC:
                cmpx = "{a} %s {b}" % FC[m]
            else:
                cmpx = "fabs{w}({a}) %s fabs{w}({b})" % (">=" if m == "facge" else ">")
            if d.kind == "fs":
                b = "0" if o[2].kind == "imm" else self.fsr(o[2])
                return [self.setbits(d, "(%s) ? (%s)-1 : 0" % (cmpx.format(a=self.fsr(o[1]), b=b, w=d.w), UT[d.w]))]
            f = FFLD[d.es]
            b = "0" if o[2].kind == "imm" else self.lane(o[2], f)
            return [self.vec(d, "(%s) ? (%s)-1 : 0" % (cmpx.format(a=self.lane(o[1], f), b=b, w=d.es), UT[d.es]))]

        # ---- integer vector
        if m in ("movi", "mvni"):
            v = o[1].v
            if len(o) > 2 and o[2].kind == "shift":
                if o[2].t == "lsl":
                    v <<= o[2].amt
                else:           # msl: ones shifted in
                    v = (v << o[2].amt) | ((1 << o[2].amt) - 1)
            if d.kind == "fs":
                return [self.setbits(d, self.imm(v, d.w))]
            if m == "mvni":
                v = ~v
            return [self.vec(d, self.imm(v, d.es))]
        if m == "dup":
            s = o[1]
            if d.kind == "fs":
                return [self.setbits(d, "v%d.%s[%d]" % (s.n, FLD[s.es], s.idx))]
            if s.kind == "ve":
                return ["{ %s e_ = v%d.%s[%d]; V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) t.%s[i] = e_; v%d = t; }"
                        % (UT[s.es], s.n, FLD[s.es], s.idx, d.cnt, FLD[d.es], d.n)]
            return [self.vec(d, "(%s)%s" % (UT[d.es], g(s)))]
        IB = {"add": "+", "sub": "-", "mul": "*", "and": "&", "orr": "|", "eor": "^"}
        if m in IB and d.kind == "v":
            if m in ("and", "orr", "eor"):
                return ["{ V t; t.q[0] = v%d.q[0] %s v%d.q[0]; t.q[1] = %s; v%d = t; }"
                        % (o[1].n, IB[m], o[2].n, "v%d.q[1] %s v%d.q[1]" % (o[1].n, IB[m], o[2].n) if d.cnt * d.es == 128 else "0", d.n)]
            if len(o) > 2 and o[2].kind == "imm":
                raise Unsupported("vector op with immediate")
            return [self.vec(d, "(%s)(%s %s %s)" % (UT[d.es], self.lane(o[1]), IB[m], self.lane(o[2])))]
        if m in IB and d.kind == "fs":      # scalar d-register integer add/sub
            return [self.setbits(d, "v%d.q[0] %s v%d.q[0]" % (o[1].n, IB[m], o[2].n))]
        if m in ("bic", "orn") and d.kind == "v":
            if o[1].kind == "imm":
                v = o[1].v << (o[2].amt if len(o) > 2 else 0)
                return [self.vec(d, "v%d.%s[i] & ~%s" % (d.n, FLD[d.es], self.imm(v, d.es)), keep=False)]
            op = "&" if m == "bic" else "|"
            return ["{ V t; t.q[0] = v%d.q[0] %s ~v%d.q[0]; t.q[1] = %s; v%d = t; }"
                    % (o[1].n, op, o[2].n, "v%d.q[1] %s ~v%d.q[1]" % (o[1].n, op, o[2].n) if d.cnt * d.es == 128 else "0", d.n)]
        if m in ("not", "mvn") and d.kind == "v":
            return ["{ V t; t.q[0] = ~v%d.q[0]; t.q[1] = %s; v%d = t; }" % (o[1].n, "~v%d.q[1]" % o[1].n if d.cnt * d.es == 128 else "0", d.n)]
        if m in ("neg", "abs") and d.kind in ("v", "fs"):
            if d.kind == "fs":
                e = "(uint64_t)(-v%d.sq[0])" % o[1].n if m == "neg" else "(uint64_t)(v%d.sq[0] < 0 ? -v%d.sq[0] : v%d.sq[0])" % (o[1].n, o[1].n, o[1].n)
                return [self.setbits(d, e)]
            s = self.lane(o[1], SFLD[d.es])
            return [self.vec(d, "(%s)(-%s)" % (UT[d.es], s) if m == "neg" else "(%s)(%s < 0 ? -%s : %s)" % (UT[d.es], s, s, s))]
        if m in ("bsl", "bit", "bif"):
            a, b = o[1].n, o[2].n
            full = d.cnt * d.es == 128
            def f(k):
                D, N, M = "v%d.q[%d]" % (d.n, k), "v%d.q[%d]" % (a, k), "v%d.q[%d]" % (b, k)
                if m == "bsl":
                    return "(%s & %s) | (~%s & %s)" % (D, N, D, M)
                if m == "bit":
                    return "(%s & ~%s) | (%s & %s)" % (D, M, N, M)
                return "(%s & %s) | (%s & ~%s)" % (D, M, N, M)
            return ["{ V t; t.q[0] = %s; t.q[1] = %s; v%d = t; }" % (f(0), f(1) if full else "0", d.n)]
        if m in ("shl", "sshr", "ushr", "sli", "ssra", "usra", "srshr", "urshr"):
            sh = o[2].v
            if d.kind == "fs":
                es, cnt = d.w, 1
                src = "v%d.%s[0]" % (o[1].n, (SFLD if m in ("sshr", "ssra") else FLD)[es])
                dst = "v%d.%s[0]" % (d.n, FLD[es])
            else:
                es, cnt = d.es, d.cnt
                src = "v%d.%s[i]" % (o[1].n, (SFLD if m in ("sshr", "ssra") else FLD)[es])
                dst = "v%d.%s[i]" % (d.n, FLD[es])
            e = {"shl": "(%s)(%s << %d)" % (UT[es], src, sh), "sshr": "(%s)(%s >> %d)" % (UT[es], src, min(sh, es - 1)),
                 "ushr": "(%s)(%s >> %d)" % (UT[es], src, sh) if sh < es else "0",
                 "sli": "(%s)((%s << %d) | (%s & %s))" % (UT[es], src, sh, dst, self.imm((1 << sh) - 1, es)),
                 "ssra": "(%s)(%s + (%s >> %d))" % (UT[es], dst, src, min(sh, es - 1)),
                 "usra": "(%s)(%s + (%s >> %d))" % (UT[es], dst, src, sh)}.get(m)
            if e is None:
                raise Unsupported("rounding shift")
            if d.kind == "fs":
                return [self.setbits(d, e)]
            return [self.vec(d, e)]
        if m in ("sshll", "sshll2", "ushll", "ushll2", "sxtl", "sxtl2", "uxtl", "uxtl2"):
            sh = o[2].v if len(o) > 2 else 0
            hi = m.endswith("2")
            sg = m[0] == "s"
            s = o[1]
            se = d.es // 2
            src = "v%d.%s[i + %d]" % (s.n, (SFLD if sg else FLD)[se], d.cnt if hi else 0)
            return [self.vec(d, "(%s)((%s)%s << %d)" % (UT[d.es], (ST if sg else UT)[d.es], src, sh))]
        if m in ("xtn", "xtn2"):
            s = o[1]
            if m == "xtn2":
                h = d.cnt // 2
                return ["{ V t = v%d; for (int i = 0; i < %d; i++) t.%s[i + %d] = (%s)v%d.%s[i]; v%d = t; }"
                        % (d.n, h, FLD[d.es], h, UT[d.es], s.n, FLD[s.es], d.n)]
            return [self.vec(d, "(%s)v%d.%s[i]" % (UT[d.es], s.n, FLD[s.es]))]
        IC = {"cmeq": "==", "cmgt": ">", "cmge": ">=", "cmhi": ">", "cmhs": ">=", "cmlt": "<", "cmle": "<="}
        if m in IC:
            sg = m not in ("cmhi", "cmhs", "cmeq")
            if d.kind == "fs":
                a = "v%d.%s[0]" % (o[1].n, (SFLD if sg else FLD)[d.w])
                b = "0" if o[2].kind == "imm" else "v%d.%s[0]" % (o[2].n, (SFLD if sg else FLD)[d.w])
                return [self.setbits(d, "(%s %s %s) ? (%s)-1 : 0" % (a, IC[m], b, UT[d.w]))]
            f = (SFLD if sg else FLD)[d.es]
            b = "0" if o[2].kind == "imm" else self.lane(o[2], f)
            return [self.vec(d, "(%s %s %s) ? (%s)-1 : 0" % (self.lane(o[1], f), IC[m], b, UT[d.es]))]
        if m == "cmtst":
            return [self.vec(d, "(%s & %s) ? (%s)-1 : 0" % (self.lane(o[1]), self.lane(o[2]), UT[d.es]))]
        if m in ("smax", "smin", "umax", "umin"):
            f = (SFLD if m[0] == "s" else FLD)[d.es]
            a, b = self.lane(o[1], f), self.lane(o[2], f)
            return [self.vec(d, "(%s)(%s %s %s ? %s : %s)" % (UT[d.es], a, ">" if m.endswith("max") else "<", b, a, b))]
        if m == "addp":
            if d.kind == "fs":
                return [self.setbits(d, "v%d.q[0] + v%d.q[1]" % (o[1].n, o[1].n))]
            h = d.cnt // 2
            f = FLD[d.es]
            return ["{ V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) { t.%s[i] = v%d.%s[2 * i] + v%d.%s[2 * i + 1]; "
                    "t.%s[i + %d] = v%d.%s[2 * i] + v%d.%s[2 * i + 1]; } v%d = t; }"
                    % (h, f, o[1].n, f, o[1].n, f, f, h, o[2].n, f, o[2].n, f, d.n)]
        if m in ("addv", "uaddlv", "saddlv", "umaxv", "uminv", "smaxv", "sminv"):
            s = o[1]
            sg = m[0] == "s"
            f = (SFLD if sg else FLD)[s.es]
            if m in ("addv", "uaddlv", "saddlv"):
                return ["{ %s a_ = 0; for (int i = 0; i < %d; i++) a_ += v%d.%s[i]; v%d = mk_%s((%s)a_); }"
                        % ("int64_t" if sg else "uint64_t", s.cnt, s.n, f, d.n, FLD[d.w], UT[d.w])]
            cmpc = ">" if "max" in m else "<"
            return ["{ %s a_ = v%d.%s[0]; for (int i = 1; i < %d; i++) if (v%d.%s[i] %s a_) a_ = v%d.%s[i]; v%d = mk_%s((%s)a_); }"
                    % ((ST if sg else UT)[s.es], s.n, f, s.cnt, s.n, f, cmpc, s.n, f, d.n, FLD[d.w], UT[d.w])]
        if m == "cnt":
            return [self.vec(d, "(uint8_t)__builtin_popcount(v%d.b[i])" % o[1].n)]
        if m == "ext":
            idx = o[3].v
            n = d.cnt
            return ["{ V t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) t.b[i] = (i + %d < %d) ? v%d.b[i + %d] : v%d.b[i + %d - %d]; v%d = t; }"
                    % (n, idx, n, o[1].n, idx, o[2].n, idx, n, d.n)]
        if m in ("rev64", "rev32", "rev16") and d.kind == "v":
            grp = int(m[3:]) // d.es
            return [self.vec(d, "v%d.%s[(i / %d) * %d + (%d - 1 - i %% %d)]" % (o[1].n, FLD[d.es], grp, grp, grp, grp))]
        if m in ("zip1", "zip2", "uzp1", "uzp2", "trn1", "trn2"):
            f = FLD[d.es]
            a, b, n = o[1].n, o[2].n, d.cnt
            h = n // 2
            part = int(m[-1]) - 1
            if m.startswith("zip"):
                e = "(i & 1) ? v%d.%s[i / 2 + %d] : v%d.%s[i / 2 + %d]" % (b, f, part * h, a, f, part * h)
            elif m.startswith("uzp"):
                e = "(i < %d) ? v%d.%s[2 * i + %d] : v%d.%s[2 * (i - %d) + %d]" % (h, a, f, part, b, f, h, part)
            else:
                e = "(i & 1) ? v%d.%s[(i & ~1) + %d] : v%d.%s[(i & ~1) + %d]" % (b, f, part, a, f, part)
            return [self.vec(d, e)]
        if m == "tbl":
            tbl = o[1].regs
            idx = o[2].n
            n = len(tbl)
            src = "".join("memcpy(tb_ + %d, &v%d, 16); " % (16 * k, r.n) for k, r in enumerate(tbl))
            return ["{ uint8_t tb_[%d]; %sV t; t.q[0] = t.q[1] = 0; for (int i = 0; i < %d; i++) t.b[i] = v%d.b[i] < %d ? tb_[v%d.b[i]] : 0; v%d = t; }"
                    % (16 * n, src, d.cnt, idx, 16 * n, idx, d.n)]
        if m in ("saddw", "uaddw", "saddw2", "uaddw2", "ssubw", "usubw", "ssubw2", "usubw2"):
            sg = m[0] == "s"
            hi = m.endswith("2")
            se = d.es // 2
            op = "+" if "add" in m else "-"
            return [self.vec(d, "(%s)(v%d.%s[i] %s (%s)v%d.%s[i + %d])" % (UT[d.es], o[1].n, FLD[d.es], op, (ST if sg else UT)[d.es], o[2].n, (SFLD if sg else FLD)[se], d.cnt if hi else 0))]
        if m in ("smull", "umull", "smull2", "umull2", "smlal", "umlal", "smlal2", "umlal2", "saddl", "uaddl", "saddl2", "uaddl2", "ssubl", "usubl", "ssubl2", "usubl2"):
            sg = m[0] == "s"
            hi = m.endswith("2")
            se = d.es // 2
            off = d.cnt if hi else 0
            T = (ST if sg else UT)[d.es]
            F = (SFLD if sg else FLD)[se]
            a = "(%s)v%d.%s[i + %d]" % (T, o[1].n, F, off)
            b = "(%s)v%d.%s[%s]" % (T, o[2].n, F, str(o[2].idx) if o[2].kind == "ve" else "i + %d" % off)
            base = m.rstrip("2")
            if base.endswith("mull"):
                e = "%s * %s" % (a, b)
            elif base.endswith("mlal"):
                e = "v%d.%s[i] + (%s)(%s * %s)" % (d.n, FLD[d.es], UT[d.es], a, b)
            elif base.endswith("addl"):
                e = "%s + %s" % (a, b)
            else:
                e = "%s - %s" % (a, b)
            return [self.vec(d, "(%s)(%s)" % (UT[d.es], e), keep=base.endswith("mlal"))]
        if m in ("sshl", "ushl"):
            sg = m[0] == "s"
            f = (SFLD if sg else FLD)[d.es]
            return [self.vec(d, "(%s)%s%d(v%d.%s[i], v%d.sb[i * %d])" % (UT[d.es], m, d.es, o[1].n, f, o[2].n, d.es // 8))]
        if m in ("mla", "mls"):
            return [self.vec(d, "(%s)(v%d.%s[i] %s %s * %s)" % (UT[d.es], d.n, FLD[d.es], "+" if m == "mla" else "-", self.lane(o[1]), self.lane(o[2])))]
        raise Unsupported("mnemonic")


# ---------------------------------------------------------------------------------------------------------
# whole program

class Translator:
    def __init__(self, images, host=(), overrides=(), stubs=(), stub_pred=None, wraps=()):
        self.wraps = set(wraps)             # symbols whose callers get H_<name>, the original staying as O_<name>
        self.stub_pred = stub_pred          # (image, address, name) -> True to replace the function by a trap
        self.stubs = set(stubs)             # (image, address) of functions replaced by a trap
        self.images = images
        self.host = set(host)               # symbols always bound to the host
        self.overrides = set(overrides)     # internal symbols replaced by a host function
        self.host_used = set()
        self.done = {}                      # (image, addr) -> C text
        self.problems = []
        self.unresolved_list = []
        self.jt_failures = []
        self.unresolved_br = 0              # functions with a computed jump that was not understood

    def call_symbol(self, fn, name):
        if name in self.overrides or name in self.host:
            self.host_used.add(name)
            return "H_%s(c);" % cname(name)
        for img in ([fn.img] + [i for i in self.images.values() if i is not fn.img]):
            a = img.exports.get(name)
            if a is not None and a in img.funcs:
                fn.callees.add((img.index, a))
                return "F_%d_%x(c);" % (img.index, a)
        self.host_used.add(name)
        return "H_%s(c);" % cname(name)

    def run(self, roots):
        work = list(roots)
        while work:
            key = work.pop()
            if key in self.done:
                continue
            img = self.images[key[0]]
            size = img.funcs.get(key[1])
            if size is None:
                self.problems.append((key, "not a function start"))
                self.done[key] = "void F_%d_%x(cpu_t *c) { a2c_trap(c, 0x%xULL, \"not a function start\"); }\n" % (key[0], key[1], key[1])
                continue
            if img.byaddr.get(key[1]) in self.overrides:
                pass        # replaced by a host function below, whatever the stub rules say
            elif key in self.stubs or (self.stub_pred and self.stub_pred(img, key[1], img.byaddr.get(key[1]))):
                self.stubbed = getattr(self, "stubbed", 0) + 1
                self.done[key] = "void F_%d_%x(cpu_t *c) { a2c_trap(c, 0x%xULL, \"stubbed out\"); }\n" % (key[0], key[1], key[1])
                continue
            # an exported symbol may be replaced by a host function
            name = img.byaddr.get(key[1])
            if name in self.overrides:
                self.host_used.add(name)
                self.done[key] = "void F_%d_%x(cpu_t *c) { H_%s(c); }\n" % (key[0], key[1], cname(name))
                continue
            f = Func(self, img, key[1], size)
            self.done[key] = f.translate()
            if name in self.wraps:
                # a faster host version stands in front; it may call the translation, O_<name>, for the cases
                # it does not handle
                me = "F_%d_%x" % key
                self.done[key] = (self.done[key].replace("void %s(cpu_t *c) {" % me, "void O_%s(cpu_t *c) {" % cname(name), 1)
                                  + "void H_%s(cpu_t *c);" % cname(name) + chr(10)
                                  + "void %s(cpu_t *c) { H_%s(c); }" % (me, cname(name)) + chr(10))
            for u in f.unsupported:
                self.problems.append((key, u))
            work.extend(f.callees)

    def write(self, path, profile=False):
        """profile=True wraps every function in a tick counter (a2c_prof_*), for finding where time goes."""
        keys = sorted(self.done)
        with open(path, "w", encoding="utf8", newline="\n") as out:
            out.write('#include "a2c_rt.h"\n\n')
            for n in sorted(self.host_used):
                out.write("void H_%s(cpu_t *c);\n" % cname(n))
            for k in keys:
                out.write("void F_%d_%x(cpu_t *c);\n" % k)
            out.write("\n")
            if profile:
                out.write("#include <x86intrin.h>\nuint64_t a2c_prof_ticks[%d], a2c_prof_calls[%d];\n" % (len(keys), len(keys)))
                out.write("const char *const a2c_prof_names[] = { %s };\nconst int a2c_prof_n = %d;\n"
                          % (", ".join('"%s"' % (self.images[k[0]].byaddr.get(k[1]) or "F_%d_%x" % k) for k in keys), len(keys)))
            for n, k in enumerate(keys):
                img = self.images[k[0]]
                out.write("/* %s */\n" % img.byaddr.get(k[1], "(local)"))
                text = self.done[k]
                if profile:
                    name = "F_%d_%x" % k
                    text = text.replace("void %s(cpu_t *c) {" % name, "static void I%s(cpu_t *c) {" % name, 1)
                    text += ("void %s(cpu_t *c) { uint64_t t_ = __rdtsc(); I%s(c); a2c_prof_ticks[%d] += __rdtsc() - t_; "
                             "a2c_prof_calls[%d]++; }\n" % (name, name, n, n))
                out.write(text)
                out.write("\n")
            out.write("const a2c_func a2c_funcs[] = {\n")
            for k in keys:
                out.write("  { IMG%d + 0x%xULL, F_%d_%x },\n" % (k[0], k[1], k[0], k[1]))
            out.write("};\nconst int a2c_nfuncs = %d;\n" % len(keys))
            out.write("const a2c_export a2c_exports[] = {\n")
            for k in keys:
                name = self.images[k[0]].byaddr.get(k[1])
                if name:
                    out.write("  { \"%s\", F_%d_%x },\n" % (name, k[0], k[1]))
            out.write("  { 0, 0 }\n};\n")
            out.write("const char *const a2c_host_names[] = { %s 0 };\n" % " ".join('"%s",' % n for n in sorted(self.host_used)))
            out.write("void (*const a2c_host_funcs[])(cpu_t *) = { %s 0 };\n" % " ".join("H_%s," % cname(n) for n in sorted(self.host_used)))

    def write_split(self, outdir, parts):
        """The same as write(), as gen_decl.h, gen_000.c ... and gen_tables.c in outdir, the functions spread over
        `parts` files of about equal size so they can be compiled in parallel. Returns the file names."""
        import os
        os.makedirs(outdir, exist_ok=True)
        keys = sorted(self.done)
        with _KeepIfSame(os.path.join(outdir, "gen_decl.h")) as out:
            out.write('#include "a2c_rt.h"\n')
            for n in sorted(self.host_used):
                out.write("void H_%s(cpu_t *c);\n" % cname(n))
            for k in keys:
                out.write("void F_%d_%x(cpu_t *c);\n" % k)
        total = sum(len(self.done[k]) for k in keys)
        names, part, size, out = [], 0, 0, None
        for k in keys:
            if out is None or (size > total / parts and part < parts):
                if out:
                    out.close()
                name = "gen_%03d.c" % part
                names.append(name)
                out = _KeepIfSame(os.path.join(outdir, name))
                out.write('#include "gen_decl.h"\n\n')
                part += 1; size = 0
            out.write("/* %s */\n" % self.images[k[0]].byaddr.get(k[1], "(local)"))
            out.write(self.done[k]); out.write("\n")
            size += len(self.done[k])
        if out:
            out.close()
        with _KeepIfSame(os.path.join(outdir, "gen_tables.c")) as out:
            out.write('#include "gen_decl.h"\n\n')
            out.write("const a2c_func a2c_funcs[] = {\n")
            for k in keys:
                out.write("  { IMG%d + 0x%xULL, F_%d_%x },\n" % (k[0], k[1], k[0], k[1]))
            out.write("};\nconst int a2c_nfuncs = %d;\n" % len(keys))
            out.write("const a2c_export a2c_exports[] = {\n")
            for k in keys:
                name = self.images[k[0]].byaddr.get(k[1])
                if name:
                    out.write("  { \"%s\", F_%d_%x },\n" % (name, k[0], k[1]))
            out.write("  { 0, 0 }\n};\n")
            out.write("const char *const a2c_host_names[] = { %s 0 };\n" % " ".join('"%s",' % n for n in sorted(self.host_used)))
            out.write("void (*const a2c_host_funcs[])(cpu_t *) = { %s 0 };\n" % " ".join("H_%s," % cname(n) for n in sorted(self.host_used)))
        names.append("gen_tables.c")
        return names


class _KeepIfSame:
    """A text file that is only rewritten if its content changed, so its timestamp tells a build what to redo."""
    def __init__(self, path):
        self.path, self.parts = path, []

    def write(self, s):
        self.parts.append(s)

    def close(self):
        import os
        text = "".join(self.parts).encode("utf8")
        if os.path.exists(self.path):
            with open(self.path, "rb") as f:
                if f.read() == text:
                    return
        with open(self.path, "wb") as f:
            f.write(text)

    def __enter__(self):
        return self

    def __exit__(self, *a):
        self.close()


def cname(n):
    return re.sub(r"[^A-Za-z0-9_]", "_", n)
